
### Criando VPC 
Resources:
  VPCAula:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

#### Criando seguendo item
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCAula
      CidrBlock: 10.0.1.0/24

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCAula
      CidrBlock: 10.0.2.0/24

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCAula
      CidrBlock: 10.0.3.0/24

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCAula
      CidrBlock: 10.0.4.0/24

### criando internetgateway
  IGW:
    Type: AWS::EC2::InternetGateway

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:  !Ref VPCAula
      InternetGatewayId: !Ref IGW

  RT:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref VPCAula

  RTtoIGW:
    Type: AWS::EC2::Route
    DependsOn: IGW
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref RT
  
  RTAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RT
      SubnetId: !Ref PublicSubnetA

### criando EC2
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0443305dabd4be2bc
      InstanceType: t2.micro
      SubnetId: !Ref PrivateSubnetA

### criando SNS
  Topico:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: "v_zorro@yahoo.com"
        Protocol: email
      TopicName: "Topico"

### criando bucket 
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: dbcloud-bucket
      LifecycleConfiguration:
        Rules:
          - Id: Glacier
            Prefix: relatorio
            Status: Enabled
            ExpirationInDays: 365
            Transitions: 
              - TransitionInDays: 1
                StorageClass: GLACIER

### criando security group 
  SGAula:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Libera porta 22
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0
        VpcId: !Ref VPCAula

#### Outuputs
Outputs:
  Bucket:
    Value: !Ref Bucket
  StackName:
    Value: !Ref AWS::StackName
  StackId:
    Value: !Ref AWS::StackId
  Region:
    Value: !Ref AWS::Region
